### ISSUE TITLE
Add a plugin for Azure AKS k8_audit 

### ISSUE THREAD

**Issue by NissesSenap** [falcosecurity/plugins#123]
**Motivation**

Just like in AWS I want to be able to monitor my k8s audit logs in Azure.

**Feature**

A implementation of reading k8s_aduit logs in AKS through [Log Analytics Workspace](https://docs.microsoft.com/en-us/azure/azure-monitor/logs/quick-create-workspace?tabs=azure-portal).

**Alternatives**

AKS also supports sending logs directly to a [storage account](https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview) and a [event hub](https://azure.microsoft.com/en-us/services/event-hubs/#features)

But to make the initial offering as similar to AWS I think starting with Log Analytics Workspace is a good idea.

**Additional context**

How to manage the Azure Diagnostic resources through terraform:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting

**Comment by NissesSenap** [comment]
I have started working on this feature.

**Comment by jasondellaluce** [comment]
While developing the current k8saudit plugin, I tried to design it so that it could be easy to develop integrations like this to fetch audit logs from managed k8s platforms. I'm excited to see the first one coming! 😄 

Note that the whole k8saudit plugin is an importable Go struct. In your case, you probably just need to re-implement the open method and reuse all the extraction-related code: https://github.com/falcosecurity/plugins/blob/52e46f7e876381f1cf666c505d386cdaa48ab2cb/plugins/k8saudit/pkg/k8saudit/source.go#L56

Let me know if you'd some help or to work together in this!

**Comment by jasondellaluce** [comment]
@NissesSenap any news? There's a WIP EKS porting that you could use as inspiration https://github.com/falcosecurity/plugins/pull/134. It took few lines of code to adapt the k8saudit plugin to the new integration.

**Comment by NissesSenap** [comment]
@jasondellaluce sadly I haven't had time to look in to this. My guess I can take a look in a month or something similar, if any one else have time please go for it.

**Comment by andreyolv** [comment]
interesting feature
