### ISSUE TITLE
alerts of a rule A depends on condition of rule different to rule A

### ISSUE THREAD

**Issue by pabloopez** [falcosecurity/plugins#57]
**Describe the bug**

The condition of the rule `List Buckets` is conditioning if alerts from other different rules (for example, `Create AWS user`, `Create Group`, etc.) are displayed.

**How to reproduce it**

1. Configure Falco as explained in #56.
2. You can use the aws_cloudtrail logs file [here](https://gist.githubusercontent.com/pabloopez/90b77bbe4feecb74edf83c437fe3dbe6/raw/c444818d8f8fff87c5bf8950156340043c3a5b63/anonimized_cloudtrail_events.json).
3. Include `enable: true` in all the rules. 
4. Modify the rule condition of the rule `List Buckets` 
to `ct.name="ListBuckets"` instead of `ct.name="ListBuckets" and not ct.error exists`.

**Expected behaviour**

The alert of a rule A depends only on the condition of the rule A and not on the condition of rules other different than A.

**Screenshots**
The next screenshot displays two consecutive executions of falco. The only difference between them is that the condition of the rule `List Buckets` is just `ct.name="ListBuckets"` in the second one. In the first one I am using the original one: `ct.name="ListBuckets" and not ct.error exists`.

![image](https://user-images.githubusercontent.com/56795889/151138246-1cb9da14-2290-4967-a953-795ee177e13f.png)

**Environment**

- Falco version:
```
Falco version: 0.30.0-155+2f82a9b
Driver version: 319368f1ad778691164d33d59945e00c5752cd27
```
- System info:
```
Wed Jan 26 09:17:48 2022: Falco version 0.30.0-155+2f82a9b (driver version 319368f1ad778691164d33d59945e00c5752cd27)
Wed Jan 26 09:17:48 2022: Falco initialized with configuration file /etc/falco/falco.yaml
Wed Jan 26 09:17:48 2022: Loading plugin (cloudtrail) from file /usr/share/falco/plugins/libcloudtrail.so
Wed Jan 26 09:17:48 2022: Loading plugin (json) from file /usr/share/falco/plugins/libjson.so
Wed Jan 26 09:17:48 2022: Loading rules from file /etc/falco/aws_cloudtrail_rules.yaml:
{
  "machine": "x86_64",
  "nodename": "host",
  "release": "5.11.0-1021-gcp",
  "sysname": "Linux",
  "version": "#23~20.04.1-Ubuntu SMP Fri Oct 1 19:04:32 UTC 2021"
}
```
- Cloud provider or hardware configuration:
- OS:
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel:
```
Linux host 5.11.0-1021-gcp #23~20.04.1-Ubuntu SMP Fri Oct 1 19:04:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Installation method:
```
dpkg DEB
```

**Additional context**

I can provide a VM with the same environment I am using to test this.

**Comment by mstemm** [comment]
This was the same problem as the first half of #56 -- a rule condition related to plugins and with a not logical operator could mistakenly result in the rule not running for any plugins at all.

All of the rules "List Buckets", "Run Instances", "Create Group", "Create AWS user", and "Delete Bucket Public Access Block" have a clause `and not ct.error exists`, and removing *any* of those clauses allows all 5 rules to match events. This is because the event types was being ORed across rules, and removing one clause adds plugin events back.

Changing plugin fields to work on all events (and knowing that they are still isolated from syscall fields via the use of filter factories) fixes this problem.

**Comment by mstemm** [comment]
I'll close this as a duplicate of #56

**Comment by pabloopez** [comment]
lgtm

**Comment by leogr** [comment]
/reopen

After a bit of investigation, this and the #56 seem to be two different problems.

Currently, we have two workarounds for the problem described by this issue (basically the bug is present when the condition uses `not` operator like in `and not ct.error exists` part of the condition):
- https://github.com/falcosecurity/libs/pull/190
- https://github.com/falcosecurity/falco/pull/1875

We will probably opt for the latter solution.

**Comment by leogr** [comment]
Fixed by https://github.com/falcosecurity/falco/pull/1875
/close
